language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-28
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-28
  - android-28
  - extra-android-m2repository
  - $ANDROID_TARGET
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - echo yes | sdkmanager "build-tools;28.0.3"
  - ./gradlew build
  - ./gradlew check
  - ./gradlew testMinSdk24DebugUnitTestCoverage
  - ./gradlew testMinSdk24ReleaseUnitTestCoverage
  - ./gradlew testMinSdk28DebugUnitTestCoverage
  - ./gradlew testMinSdk28ReleaseUnitTestCoverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
