name: Android WebRTC SDK CI with Gradle

on:
  push:
    branches: 
      - master
      - add-gha
  pull_request:
    branches:
      - master

jobs:
  ubuntu-qemu-android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Install dependencies
        run: sudo apt-get -y install gcc-arm-linux-gnueabi g++-arm-linux-gnueabi binutils-arm-linux-gnueabi
      - name: Checkout Android SDK branch
        uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          java-version: 1.8
      - name: Setup toolchain
        uses: maxim-lobanov/setup-android-tools@v1
        with:
          packages: |
            platforms;android-28
            system-images;android-28;default;arm64-v8a
            build-tools;28.0.3
            extras;android;m2repository
      - name: Permission to gradle File
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build jacocoTestReport assembleAndroidTest --stacktrace
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)
