name: Producer SDK Android CI with Gradle

on:
  push:
    branches: 
      - master
      - add-gha
  pull_request:
    branches:
      - master
      - add-gha

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          java-version: 1.8
      - name: Setup toolchain
        uses: maxim-lobanov/setup-android-tools@v1
        with:
          packages: |
            platforms;android-28
            system-images;android-28;default;arm64-v8a
      - name: Permission to gradle File
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build jacocoTestReport assembleAndroidTest
